export const AUTHENICATION_LOGIN = "AUTHENICATION LOGIN";
export const AUTHENICATION_LOGIN_SUCCESS = "AUTHENICATION LOGIN SUCCESS";
export const AUTHENICATION_LOGIN_FAILED = "AUTHENICATION LOGIN FAILED";
export const AUTHENICATION_LOGOUT = "AUTHENICATION LOGOUT";
export const AUTHENICATION_LOGOUT_SUCCESS = "AUTHENICATION LOGOUT SUCCESS";
export const AUTHENICATION_LOGOUT_FAILED = "AUTHENICATION LOGOUT FAILED";